# Generated by Django 6.0.5 on 2026-05-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.CharField(default='white', max_length=5),
        ),
    ]
