# Generated by Django 6.0.5 on 2026-05-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_state',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR'),
        ),
    ]
