# Generated by Django 6.0.5 on 2026-05-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_board_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='White_player',
            new_name='white_player',
        ),
        migrations.AlterField(
            model_name='game',
            name='board_state',
            field=models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1'),
        ),
    ]
