# Generated by Django 6.0.5 on 2026-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_white_player_game_white_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_time',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='game',
            name='last_move_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='white_time',
            field=models.IntegerField(default=600),
        ),
    ]
