# Generated by Django 6.0.5 on 2026-05-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_black_time_game_last_move_time_game_white_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
