# Generated by Django 6.0.5 on 2026-05-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
