# Generated by Django 6.0.5 on 2026-05-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_alter_move_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='move_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='move',
            name='san',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
